server:
  port: 8070
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: users
jwt:
  secret: b10bac_super_secret_key_which_is_long_enough_please_change
  expiration-ms: 86400000
  refresh-token:
    secret: b10bac_refresh_super_secret_key_which_is_long_enough_please_change
    expiration-ms: 604800000
